const Patients_information_ALL = gql
`{
  patient(id: "cjrn4pbqf000001qgbahh193o") {
    firstName
    lastName
    age
    careGiver{
      firstName
      lastName
    }
    events
    medicationList{
      items{
        drugName
        drugDosage
        drugFrequency
        drugLastAdmin
        drugEffectiveDuration
      }
    }
  }
}`;

const patient_Client_List = gql`
{
  patient(id:"cjrn4pbqf000001qgbahh193o"){
    client{
      firstName
      lastName
    }
  }
}`; 